opt_out_usage

ENV["PRODUCTION_BUNDLE_ID_MAIN"] = "com.whoisup.app"
ENV["PRODUCTION_BUNDLE_ID_NS"]  = "com.whoisup.app.NotificationService"
ENV["PRODUCTION_PROFILE_NAME_MAIN"] = "GitHub Actions Distribution - Production"
ENV["PRODUCTION_PROFILE_NAME_NS"]  = "GitHub Actions Distribution - Production - NS"

ENV["STAGING_BUNDLE_ID_MAIN"] = "com.whoisup.app.qa"
ENV["STAGING_BUNDLE_ID_NS"]  = "com.whoisup.app.qa.NotificationService"
ENV["STAGING_PROFILE_NAME_MAIN"] = "GitHub Actions Distribution - Staging"
ENV["STAGING_PROFILE_NAME_NS"]  = "GitHub Actions Distribution - Staging - NS"

platform :ios do 
  desc "Build staging and upload to TestFlight for internal testing"
  lane :staging do

    # log versions used
    sh("swift --version")
    sh("xcodebuild -version")

    # generate auth token
    app_store_connect_api_key(
      issuer_id: ENV["ISSUER_ID"],
      key_id: ENV["KEY_ID"],
      key_content: ENV["KEY_CONTENT_BASE64"],
      is_key_content_base64: true
    )

    # get current app version
    current_version = get_current_ios_version_code()
    # get latest app store build number for this version
    last_app_store_build_number = app_store_build_number(
      live: false,
      app_identifier: ENV["STAGING_BUNDLE_ID_MAIN"],
      version: current_version,
      initial_build_number: 0
    )

    # set build number to last one + 1
    increment_build_number(
      build_number: last_app_store_build_number + 1,
      xcodeproj: "ios/App/App.xcodeproj"
    )

    # update project provisioning `NotificationService` target manually
    update_project_provisioning(
      xcodeproj: "ios/App/App.xcodeproj",
      profile: "/Users/runner/Library/MobileDevice/Provisioning Profiles/com.whoisup.app.qa.notificationservice.mobileprovision",
      target_filter: "NotificationService",
      build_configuration: "Staging",
      code_signing_identity: "Apple Distribution"
    )

    # manual code signing

    # Main App
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "ios/App/App.xcodeproj",
      targets: ["Amigos"],
      team_id: "G3578K4W58",
      code_sign_identity: "Apple Distribution",
      bundle_identifier: ENV["STAGING_BUNDLE_ID_MAIN"],
      profile_name: ENV["STAGING_PROFILE_NAME_MAIN"]
    )

    # NotificationService Extension
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "ios/App/App.xcodeproj",
      targets: ["NotificationService"],
      team_id: "G3578K4W58",
      code_sign_identity: "Apple Distribution",
      bundle_identifier: ENV["STAGING_BUNDLE_ID_NS"],
      profile_name: ENV["STAGING_PROFILE_NAME_NS"]
    )

    build_app(
      workspace: "ios/App/App.xcworkspace",
      scheme: "App Staging",
      configuration: "Staging",
      xcargs: "-allowProvisioningUpdates -skipPackagePluginValidation -skipMacroValidation",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          ENV["STAGING_BUNDLE_ID_MAIN"] => ENV["STAGING_PROFILE_NAME_MAIN"],
          ENV["STAGING_BUNDLE_ID_NS"] => ENV["STAGING_PROFILE_NAME_NS"]
        }
      }
    )
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end

platform :ios do
  desc "Build production and upload to App Store for release"
  lane :production do

    # log versions used
    sh("swift --version")
    sh("xcodebuild -version")

    # generate auth token
    app_store_connect_api_key(
      issuer_id: ENV["ISSUER_ID"],
      key_id: ENV["KEY_ID"],
      key_content: ENV["KEY_CONTENT_BASE64"],
      is_key_content_base64: true
    )

    # get current app version
    current_version = get_current_ios_version_code()
    # get latest app store build number for this version
    last_app_store_build_number = app_store_build_number(
      live: false,
      app_identifier: ENV["PRODUCTION_BUNDLE_ID_MAIN"],
      version: current_version,
      initial_build_number: 0
    )

    # set build number to last one + 1
    increment_build_number(
      build_number: last_app_store_build_number + 1,
      xcodeproj: "ios/App/App.xcodeproj"
    )

    # update project provisioning `NotificationService` target manually
    update_project_provisioning(
      xcodeproj: "ios/App/App.xcodeproj",
      profile: "/Users/runner/Library/MobileDevice/Provisioning Profiles/com.whoisup.app.notificationservice.mobileprovision",
      target_filter: "NotificationService",
      build_configuration: "Release",
      code_signing_identity: "Apple Distribution"
    )

    # manual code signing

    # Main App
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "ios/App/App.xcodeproj",
      targets: ["Amigos"],
      team_id: "G3578K4W58",
      code_sign_identity: "Apple Distribution",
      bundle_identifier: ENV["PRODUCTION_BUNDLE_ID_MAIN"],
      profile_name: ENV["PRODUCTION_PROFILE_NAME_MAIN"]
    )

    # NotificationService Extension
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "ios/App/App.xcodeproj",
      targets: ["NotificationService"],
      team_id: "G3578K4W58",
      code_sign_identity: "Apple Distribution",
      bundle_identifier: ENV["PRODUCTION_BUNDLE_ID_NS"],
      profile_name: ENV["PRODUCTION_PROFILE_NAME_NS"]
    )

    build_app(
      workspace: "ios/App/App.xcworkspace",
      scheme: "App",
      configuration: "Release",
      xcargs: "-allowProvisioningUpdates -skipPackagePluginValidation -skipMacroValidation",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          ENV["PRODUCTION_BUNDLE_ID_MAIN"] => ENV["PRODUCTION_PROFILE_NAME_MAIN"],
          ENV["PRODUCTION_BUNDLE_ID_NS"] => ENV["PRODUCTION_PROFILE_NAME_NS"]
        }
      }
    )
    upload_to_testflight(skip_waiting_for_build_processing: true)
    # TODO: Add options to wait for processing, add internal test group and avoid submitting for review.
    # Make use of key like: `api_key = app_store_connect_api_key(...)`
  end
end

platform :android do
  desc "Build and upload to Play Store Internal Testing"
  lane :internal do
    # Version code and version name for a release must be defined in `build.gradle`

    gradle(
      task: "bundle",
      project_dir: "android/",
      flags: "--quiet",
      build_type: "Release",
      properties: {
        "android.injected.signing.store.file" => ENV['KEYSTORE_PATH'],
        "android.injected.signing.store.password" => ENV['KEYSTORE_PASSWORD'],
        "android.injected.signing.key.alias" => ENV['KEYSTORE_ALIAS'],
        "android.injected.signing.key.password" => ENV['KEY_ALIAS_PASSWORD']
      }
    )
    upload_to_play_store(
      track: "internal"
    )
  end

  def get_current_ios_version_code
    # TODO: see if this works
    # Run xcodebuild command to get the version
    # version = `xcodebuild -showBuildSettings -workspace ios/App/App.xcworkspace -scheme App | grep MARKETING_VERSION | awk '{print $3}'`.strip
    # return version

    # For now, return the latest version manually.
    return "1.9.29"
  end
end
