opt_out_usage

ENV["BUNDLE_ID_MAIN_QA"] = "com.whoisup.app.qa"
ENV["BUNDLE_ID_NS_QA"]  = "com.whoisup.app.qa.NotificationService"

platform :ios do 
  desc "Build QA and upload to TestFlight for beta testing"
  lane :qa do

    # log versions used
    sh("swift --version")
    sh("xcodebuild -version")

    # generate auth token
    app_store_connect_api_key(
      issuer_id: ENV["ISSUER_ID"],
      key_id: ENV["KEY_ID"],
      key_content: ENV["KEY_CONTENT_BASE64"],
      is_key_content_base64: true
    )

    # get current app version
    current_version = get_current_ios_version_code()
    # get latest app store build number for this version
    last_app_store_build_number = app_store_build_number(
      live: false,
      app_identifier: ENV["BUNDLE_ID_MAIN_QA"],
      version: current_version,
      initial_build_number: 0
    )

    # set build number to last one + 1
    increment_build_number(
      build_number: last_app_store_build_number + 1,
      xcodeproj: "ios/App/App.xcodeproj"
    )

    # update project provisioning `NotificationService` target manually
    update_project_provisioning(
     xcodeproj: "ios/App/App.xcodeproj",
     profile: "/Users/runner/Library/MobileDevice/Provisioning Profiles/com.whoisup.app.qa.notificationservice.mobileprovision",
     target_filter: "NotificationService",
     build_configuration: "QA",
     code_signing_identity: "Apple Distribution"
    )

    # manual code signing

    # Main App
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "ios/App/App.xcodeproj",
      targets: ["Amigos"],
      team_id: "G3578K4W58",
      code_sign_identity: "Apple Distribution",
      bundle_identifier: ENV["BUNDLE_ID_MAIN_QA"],
      profile_name: "Github Actions Distribution QA"
    )

    # NotificationService Extension
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "ios/App/App.xcodeproj",
      targets: ["NotificationService"],
      team_id: "G3578K4W58",
      code_sign_identity: "Apple Distribution",
      bundle_identifier: ENV["BUNDLE_ID_NS_QA"],
      profile_name: "GitHub Actions Distribution QA - NS"
    )

   build_app(
      workspace: "ios/App/App.xcworkspace",
      scheme: "App QA",
      configuration: "QA",
      xcargs: "-allowProvisioningUpdates -skipPackagePluginValidation -skipMacroValidation",
      export_method: "app-store",
      export_options: {
      provisioningProfiles: {
        ENV["BUNDLE_ID_MAIN_QA"] => "GitHub Actions Distribution",
 	      ENV["BUNDLE_ID_NS_QA"] => "GitHub Actions Distribution - Notification Service",
        }
      } 
    )
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end

platform :ios do
  desc "Build and upload to TestFlight for internal testing"
  lane :internal do
    # log versions used
    sh("swift --version")
    sh("xcodebuild -version")
    # generate auth token
    app_store_connect_api_key(
      issuer_id: ENV["ISSUER_ID"],
      key_id: ENV["KEY_ID"],
      key_content: ENV["KEY_CONTENT_BASE64"],
      is_key_content_base64: true
    )
    # get current app version
    current_version = get_current_ios_version_code()
    # get latest app store build number for this version
    last_app_store_build_number = app_store_build_number(
      live: false,
      app_identifier: "com.whoisup.app",
      version: current_version,
      initial_build_number: 0
    )
    # set build number to last one + 1
    increment_build_number(
      build_number: last_app_store_build_number + 1,
      xcodeproj: "ios/App/App.xcodeproj"
    )

    # update project provisioning `NotificationService` target manually
    update_project_provisioning(
     xcodeproj: "ios/App/App.xcodeproj",
     profile: "/Users/runner/Library/MobileDevice/Provisioning Profiles/com.whoisup.app.notificationservice.mobileprovision",
     target_filter: "NotificationService",
     build_configuration: "Release",
     code_signing_identity: "Apple Distribution"
    )

    # manual code signing

    # Main App
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "ios/App/App.xcodeproj",
      targets: ["Amigos"],
      team_id: "G3578K4W58",
      code_sign_identity: "Apple Distribution",
      bundle_identifier: "com.whoisup.app",
      profile_name: "GitHub Actions Distribution"
    )
    
    # NotificationService Extension
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "ios/App/App.xcodeproj",
      targets: ["NotificationService"],
      team_id: "G3578K4W58",
      code_sign_identity: "Apple Distribution",
      bundle_identifier: "com.whoisup.app.NotificationService",
      profile_name: "GitHub Actions Distribution - Notification Service"
    )

    build_app(
      workspace: "ios/App/App.xcworkspace",
      scheme: "App",
      configuration: "Release",
      xcargs: "-allowProvisioningUpdates -skipPackagePluginValidation -skipMacroValidation",
      export_method: "app-store", # or "development" or "ad-hoc"
      export_options: {
        provisioningProfiles: {
          "com.whoisup.app" => "GitHub Actions Distribution",
 	  "com.whoisup.app.NotificationService" => "GitHub Actions Distribution - Notification Service",
        }
      } 
    ) 
    upload_to_testflight(skip_waiting_for_build_processing: true)
    # TODO: Add options to wait for processing, add internal test group and avoid submitting for review.
    # Make use of key like: `api_key = app_store_connect_api_key(...)`
  end
end

platform :android do
  desc "Build and upload to Play Store Internal Testing"
  lane :internal do
    # Version code and version name for a release must be defined in `build.gradle`

    gradle(
      task: "bundle",
      project_dir: "android/",
      flags: "--quiet",
      build_type: "Release",
      properties: {
        "android.injected.signing.store.file" => ENV['KEYSTORE_PATH'],
        "android.injected.signing.store.password" => ENV['KEYSTORE_PASSWORD'],
        "android.injected.signing.key.alias" => ENV['KEYSTORE_ALIAS'],
        "android.injected.signing.key.password" => ENV['KEY_ALIAS_PASSWORD']
      }
    )
    upload_to_play_store(
      track: "internal"
    )
  end

  def get_current_ios_version_code
    # TODO: see if this works
    # Run xcodebuild command to get the version
    # version = `xcodebuild -showBuildSettings -workspace ios/App/App.xcworkspace -scheme App | grep MARKETING_VERSION | awk '{print $3}'`.strip
    # return version

    # For now, return the latest version manually.
    return "1.9.28"
  end
end
