name: iOS Build (reusable)

on:
  workflow_call:
    inputs:
      app_frontend_url:
        required: true
        type: string
      package_name:
        required: true
        type: string
      environment:
        required: true
        type: string
      lane:
        required: true
        type: string
      node_env:
        required: false
        type: string

jobs:
  build:
    name: Build
    environment: ${{ inputs.environment }}
    runs-on: macos-26

    env:
      APP_FRONTEND_URL: ${{ inputs.app_frontend_url }}
      PACKAGE_NAME: ${{ inputs.package_name }}

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_26.2.app

      - name: Print Xcode version
        run: xcodebuild -version

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps

      - name: Install Bundler 2.7.2
        run: |
          gem install bundler:2.7.2

      - name: Install Ruby gems
        run: |
          bundle _2.7.2_ install

      - name: Prepare iOS project
        run: |
          if [ -n "${{ inputs.node_env }}" ]; then
            echo "Using NODE_ENV=${{ inputs.node_env }}"
            NODE_ENV=${{ inputs.node_env }} npx cap sync ios
          else
            echo "No NODE_ENV provided, running plain cap sync"
            npx cap sync ios
          fi

      - name: Generate random keychain password
        run: |
          echo "KEYCHAIN_PASSWORD=$(openssl rand -base64 20)" >> $GITHUB_ENV

      - name: Install the Apple certificate and provisioning profiles
        env:
          IOS_CERTIFICATE_BASE64: ${{ secrets.IOS_CERTIFICATE_BASE64 }}
          IOS_CERTIFICATE_PASSWORD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          IOS_PROVISIONING_PROFILE_BASE64: ${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}
          IOS_NOTIFICATION_PROVISIONING_PROFILE_BASE64: ${{ secrets.IOS_NOTIFICATION_PROVISIONING_PROFILE_BASE64 }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/$PACKAGE_NAME.mobileprovision
          NOTIF_PP_PATH=$RUNNER_TEMP/$PACKAGE_NAME.notificationservice.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # clean old provisioning profiles
          rm -rf ~/Library/MobileDevice/Provisioning\ Profiles/*

          # import certificate and provisioning profiles from secrets
          echo -n "$IOS_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$IOS_PROVISIONING_PROFILE_BASE64" | base64 --decode -o $PP_PATH
          echo -n "$IOS_NOTIFICATION_PROVISIONING_PROFILE_BASE64" | base64 --decode -o $NOTIF_PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$IOS_CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profiles
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
          cp $NOTIF_PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

          # List identities in the keychain and log the codesigning identity name
          security find-identity -p codesigning -v $KEYCHAIN_PATH

      - name: Build and Upload to TestFlight
        env:
          APP_FRONTEND_URL: ${{ env.APP_FRONTEND_URL }}
          ISSUER_ID: ${{ secrets.IOS_APP_STORE_CONNECT_ISSUER_ID }}
          KEY_ID: ${{ secrets.IOS_APP_STORE_CONNECT_KEY_ID }}
          KEY_CONTENT_BASE64: ${{ secrets.IOS_APP_STORE_CONNECT_API_KEY_BASE64 }}
        run: |
          bundle exec fastlane ios ${{ inputs.lane }}

      - name: Upload Xcode build logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: xcode-build-log
          path: /Users/runner/Library/Logs/gym/
